name: publish

on:
  release:
    types: [published]

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Extract Version from Tag
        id: split_tag
        run: |
          tag=${{ github.event.release.tag_name }}
          parts=(${tag//\// })
          echo "mc_version=${parts[0]}" >> $GITHUB_OUTPUT
          echo "mod_version=${parts[1]}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Build with Gradle
        run: ./gradlew -Psemver='${{ steps.split_tag.outputs.mod_version }}' build
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Add Artifacts to Github Release
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./build/libs/*.jar"]'
